export default [
  {
    id: 1,
    name: "香浓咖啡屋",
    simpleTitle: "手工研磨，香醇浓郁",
    desc: "提供各式手工咖啡\n温馨舒适的环境\n专业咖啡师现场制作",
    smallImg: "/static/images/网络.png",
    online: "08:00",
    offline: "22:00",
    star: false,
    imageList: [
      "/static/images/s1.jpg",
      "/static/images/s2.jpg",
      "/static/images/s3.jpg",
    ],
  },
  {
    id: 2,
    name: "咖啡时光",
    simpleTitle: "慢享时光，品味咖啡",
    desc: "精选咖啡豆\n优雅安静的阅读区\n提供多种甜点搭配",
    smallImg: "/static/images/网络.png",
    online: "09:30",
    offline: "21:00",
    star: false,
    imageList: [
      "/static/images/s1.jpg",
      "/static/images/s2.jpg",
      "/static/images/s3.jpg",
    ],
  },
  {
    id: 3,
    name: "蓝山咖啡阁",
    simpleTitle: "蓝山风味，香滑细腻",
    desc: "专注蓝山咖啡\n宽敞明亮的用餐区\n提供外卖服务",
    smallImg: "/static/images/网络.png",
    online: "10:00",
    offline: "20:00",
    star: false,
    imageList: [
      "/static/images/s1.jpg",
      "/static/images/s2.jpg",
      "/static/images/s3.jpg",
    ],
  },
  {
    id: 4,
    name: "摩卡小屋",
    simpleTitle: "摩卡风情，浓郁香醇",
    desc: "手工拉花艺术\n丰富的咖啡品种选择\n舒适休闲的氛围",
    smallImg: "/static/images/网络.png",
    online: "07:30",
    offline: "23:00",
    star: false,
    imageList: ["https://example.com/carousel-10.jpg"],
  },
  {
    id: 5,
    name: "卡布奇诺轩",
    simpleTitle: "卡布奇诺，浓情蜜意",
    desc: "独家特调咖啡\n宽敞户外座位区\n适合朋友聚会",
    smallImg: "/static/images/网络.png",
    online: "09:00",
    offline: "22:30",
    star: false,
    imageList: [
      "/static/images/s1.jpg",
      "/static/images/s2.jpg",
      "/static/images/s3.jpg",
    ],
  },
  {
    id: 6,
    name: "意式咖啡坊",
    simpleTitle: "传统意式，香浓可口",
    desc: "意式咖啡机现场制作\n多种意大利小吃搭配\n友好热情的服务",
    smallImg: "/static/images/网络.png",
    online: "08:30",
    offline: "21:30",
    star: false,
    imageList: [
      "/static/images/s1.jpg",
      "/static/images/s2.jpg",
      "/static/images/s3.jpg",
    ],
  },
  {
    id: 7,
    name: "时光咖啡吧",
    simpleTitle: "品味时光，香醇咖啡",
    desc: "经典咖啡系列\n舒适休闲的聚会场所\n提供无线上网服务",
    smallImg: "/static/images/网络.png",
    online: "08:00",
    offline: "22:00",
    star: false,
    imageList: [
      "/static/images/s1.jpg",
      "/static/images/s2.jpg",
      "/static/images/s3.jpg",
    ],
  },
  {
    id: 8,
    name: "咖啡驿站",
    simpleTitle: "驿站小憩，咖啡相伴",
    desc: "手工研磨咖啡\n独特的装修风格\n适合短暂停留",
    smallImg: "/static/images/网络.png",
    online: "09:00",
    offline: "23:00",
    star: false,
    imageList: [
      "/static/images/s1.jpg",
      "/static/images/s2.jpg",
      "/static/images/s3.jpg",
    ],
  },
  {
    id: 9,
    name: "浓情咖啡屋",
    simpleTitle: "浓情蜜意，咖啡时光",
    desc: "特色咖啡饮品\n优雅的用餐环境\n提供咖啡制作课程",
    smallImg: "/static/images/网络.png",
    online: "08:30",
    offline: "22:30",
    star: false,
    imageList: [
      "/static/images/s1.jpg",
      "/static/images/s2.jpg",
      "/static/images/s3.jpg",
    ],
  },
  {
    id: 10,
    name: "悦来咖啡坊",
    simpleTitle: "悦来悦享，咖啡时光",
    desc: "精选进口咖啡豆\n宽敞明亮的室内环境\n定期举办咖啡文化活动",
    smallImg: "/static/images/网络.png",
    online: "09:30",
    offline: "21:00",
    star: false,
    imageList: [
      "/static/images/s1.jpg",
      "/static/images/s2.jpg",
      "/static/images/s3.jpg",
    ],
  },
];
