export default [
  {
    id: 1,
    name: "香浓咖啡屋",
    simpleTitle: "手工研磨，香醇浓郁",
    desc: "提供各式手工咖啡\n温馨舒适的环境\n专业咖啡师现场制作",
    smallImg: "/static/images/网络.png",
    online: "08:00",
    offline: "22:00",
    star: false,
    imageList: [
      "/static/images/s1.jpg",
      "/static/images/s2.jpg",
      "/static/images/s3.jpg",
    ],
  },
  {
    id: 2,
    name: "瑞辛咖啡",
    simpleTitle: "店员态度很专业热情，又问必答",
    desc: "新零售专业咖啡运营商，致力推动咖啡消费在国内的普及和发展",
    smallImg: "/static/images/stores/瑞辛店面.jpg",
    online: "7:00",
    offline: "20:30",
    star: false,
    imageList: ["/static/images/stores/瑞辛轮播.jpg"],
  },
  {
    id: 3,
    name: "库迪咖啡(佳芬天地店)",
    simpleTitle: "以咖啡、饮品、冰淇淋、热狗等为主要产品进行销售",
    desc: "COTTI源自意大利特色饼干Biscotti，是一杯咖啡的佐食，\n是咖啡概念的伸展和外延，所以COTTI COFFEE 从一开始，就注定不是“又”一家咖啡店而已，\n而是一种全新的泛咖啡化的生活方式。",
    smallImg: "/static/images/stores/库迪店面.jpg",
    online: "8:30",
    offline: "22:00",
    star: false,
    imageList: ["/static/images/stores/库迪轮播.jpg"],
  },
  {
    id: 4,
    name: "Loft Coffee",
    simpleTitle: "精品咖啡，店铺装修风格独特",
    desc: "工业风格装修，摆设出彩，咖啡种类多，有独创从产品",
    smallImg: "/static/images/stores/loft店面.jpg",
    online: "8:00",
    offline: "17:00",
    star: false,
    imageList: ["/static/images/stores/loft轮播.jpg"],
  },
  {
    id: 5,
    name: "星巴克（佳芬天地店）",
    simpleTitle: "致力于商业道德采购和烘焙的咖啡",
    desc: "星巴克致力于发展成为一家与众不同的公司：在传承经典咖啡文化的\n同时，关爱伙伴，为顾客提供不同的星巴克体验",
    smallImg: "/static/images/stores/星巴克店面.jpg",
    online: "10:00",
    offline: "21:30",
    star: false,
    imageList: ["/static/images/stores/星巴克轮播.jpg"],
  },
  {
    id: 6,
    name: "SAN.Q COFFEE",
    simpleTitle: "装修风格好，物美价廉",
    desc: "精品咖啡，服务至上，精品原料，制作品质",
    smallImg: "/static/images/stores/sanQ店面.jpg",
    online: "08:30",
    offline: "20:00",
    star: false,
    imageList: ["/static/images/stores/sanQ轮播.jpg"],
  },
  {
    id: 7,
    name: "咖啡时光",
    simpleTitle: "慢享时光，品味咖啡",
    desc: "精选咖啡豆\n优雅安静的阅读区\n提供多种甜点搭配",
    smallImg: "/static/images/网络.png",
    online: "09:30",
    offline: "21:00",
    star: false,
    imageList: [
      "/static/images/s1.jpg",
      "/static/images/s2.jpg",
      "/static/images/s3.jpg",
    ],
  },
  {
    id: 8,
    name: "蓝山咖啡阁",
    simpleTitle: "蓝山风味，香滑细腻",
    desc: "专注蓝山咖啡\n宽敞明亮的用餐区\n提供外卖服务",
    smallImg: "/static/images/网络.png",
    online: "10:00",
    offline: "20:00",
    star: false,
    imageList: [
      "/static/images/s1.jpg",
      "/static/images/s2.jpg",
      "/static/images/s3.jpg",
    ],
  },
  {
    id: 9,
    name: "摩卡小屋",
    simpleTitle: "摩卡风情，浓郁香醇",
    desc: "手工拉花艺术\n丰富的咖啡品种选择\n舒适休闲的氛围",
    smallImg: "/static/images/网络.png",
    online: "07:30",
    offline: "23:00",
    star: false,
    imageList: ["https://example.com/carousel-10.jpg"],
  },
  {
    id: 10,
    name: "卡布奇诺轩",
    simpleTitle: "卡布奇诺，浓情蜜意",
    desc: "独家特调咖啡\n宽敞户外座位区\n适合朋友聚会",
    smallImg: "/static/images/网络.png",
    online: "09:00",
    offline: "22:30",
    star: false,
    imageList: [
      "/static/images/s1.jpg",
      "/static/images/s2.jpg",
      "/static/images/s3.jpg",
    ],
  },
  {
    id: 11,
    name: "意式咖啡坊",
    simpleTitle: "传统意式，香浓可口",
    desc: "意式咖啡机现场制作\n多种意大利小吃搭配\n友好热情的服务",
    smallImg: "/static/images/网络.png",
    online: "08:30",
    offline: "21:30",
    star: false,
    imageList: [
      "/static/images/s1.jpg",
      "/static/images/s2.jpg",
      "/static/images/s3.jpg",
    ],
  },
  {
    id: 12,
    name: "时光咖啡吧",
    simpleTitle: "品味时光，香醇咖啡",
    desc: "经典咖啡系列\n舒适休闲的聚会场所\n提供无线上网服务",
    smallImg: "/static/images/网络.png",
    online: "08:00",
    offline: "22:00",
    star: false,
    imageList: [
      "/static/images/s1.jpg",
      "/static/images/s2.jpg",
      "/static/images/s3.jpg",
    ],
  },
  {
    id: 13,
    name: "咖啡驿站",
    simpleTitle: "驿站小憩，咖啡相伴",
    desc: "手工研磨咖啡\n独特的装修风格\n适合短暂停留",
    smallImg: "/static/images/网络.png",
    online: "09:00",
    offline: "23:00",
    star: false,
    imageList: [
      "/static/images/s1.jpg",
      "/static/images/s2.jpg",
      "/static/images/s3.jpg",
    ],
  },
  {
    id: 14,
    name: "浓情咖啡屋",
    simpleTitle: "浓情蜜意，咖啡时光",
    desc: "特色咖啡饮品\n优雅的用餐环境\n提供咖啡制作课程",
    smallImg: "/static/images/网络.png",
    online: "08:30",
    offline: "22:30",
    star: false,
    imageList: [
      "/static/images/s1.jpg",
      "/static/images/s2.jpg",
      "/static/images/s3.jpg",
    ],
  },
  {
    id: 15,
    name: "悦来咖啡坊",
    simpleTitle: "悦来悦享，咖啡时光",
    desc: "精选进口咖啡豆\n宽敞明亮的室内环境\n定期举办咖啡文化活动",
    smallImg: "/static/images/网络.png",
    online: "09:30",
    offline: "21:00",
    star: false,
    imageList: [
      "/static/images/s1.jpg",
      "/static/images/s2.jpg",
      "/static/images/s3.jpg",
    ],
  },
];
